# Generated by Django 5.2 on 2025-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_version',
            field=models.IntegerField(default=1),
        ),
    ]
