# Generated by Django 5.2 on 2025-05-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_userprofile_password_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_version',
        ),
    ]
