# Generated by Django 4.2.7 on 2025-04-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KartavyaMain', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
