# Generated by Django 4.2.7 on 2025-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KartavyaMain', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
